version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "9445:9445"
    volumes:
      - ./bitwarden:/data:rw
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURITY=${SMTP_SECURITY}
      - SMTP_TIMEOUT=${SMTP_TIMEOUT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - DOMAIN=https://${DOMAIN}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host("${DOMAIN}")
      - traefik.http.routers.vaultwarden.entrypoints=web
      - traefik.http.services.vaultwarden.loadbalancer.server.port=9445
networks:
  dokploy-network:
    external: true
